---
# tasks file of ansible-role jonaspammer.core_dependencies

- name: Update cache and Install system packages.
  ansible.builtin.package:
    name: "{{ core_dependencies__packages }}"
    state: present
    update_cache: true
  notify:
    - gather facts

- name: reset connetion
  ansible.builtin.meta: reset_connection

- name: Try to install pip packages.
  ansible.builtin.pip:
    name: "{{ core_dependencies__pip_packages }}"
    state: present
  failed_when: false
  notify:
    - gather facts

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
