---
# vars file of ansible-role jonaspammer.core_dependencies
# (tl;dr: almost not overwrite-able variables)

core_dependencies__shared_packages:
  - acl # ansible.builtin.archive
  - at
  - bzip2 # ansible.builtin.archive
  - bash # ansible.builtin.shell (a system without bash is not usable ;) )
  - git # ansible.builtin.git
  - gzip # ansible.builtin.archive
  - tar # ansible.builtin.unarchive
  - unzip # ansible.builtin.unarchive

# `ip` binary used as per:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html#package-requirements-for-fact-gathering
_core_dependencies__specific_packages:
  Alpine:
    - iproute2 # `ip` binary
    - shadow # ansible.builtin.user
    - subversion # ansible.builtin.subversion
    - xz # ansible.builtin.archive
  Amazon_2018:
    - iproute # `ip` binary
    - shadow-utils # ansible.builtin.user
    - xz # ansible.builtin.archive
  Amazon_2:
    - iproute # `ip` binary
    - shadow-utils # ansible.builtin.user
    - xz # ansible.builtin.archive
  Debian:
    - apt-transport-https # ansible.builtin.apt_repository (not stated explicitly but obvious)
    - debconf # ansible.builtin.debconf
    # (was debconf-utils)
    - debconf-i18n # ansible.builtin.debconf
    - iproute2 # `ip` binary
    - passwd # ansible.builtin.user
    - python3-apt # ansible.builtin.apt
    - subversion # ansible.builtin.subversion
    # (deb parameter "Requires the xz-utils package to extract the control file of the deb package to install.")
    - xz-utils # ansible.builtin.apt
  RedHat_7:
    - iproute # `ip` binary
    - libselinux-python # ansible.posix.seboolean
    - libsemanage-python # ansible.posix.seboolean
    - shadow-utils # ansible.builtin.user
    - xz # ansible.builtin.archive
    - yum # ansible.builtin.yum
  RedHat: &redhat_packages
    - dnf # ansible.builtin.dnf
    - iproute # `ip` binary
    - python3-dnf # ansible.builtin.dnf
    - python3-libselinux # ansible.posix.seboolean
    - python3-libsemanage # ansible.posix.seboolean
    - shadow-utils # ansible.builtin.user
    - xz # ansible.builtin.archive
  Rocky: *redhat_packages
  Suse:
    - iproute2 # `ip` binary
    - libselinux1 # ansible.posix.seboolean
    - python3-selinux # ansible.posix.seboolean
    - shadow # ansible.builtin.user
    - subversion # ansible.builtin.subversion
    - xz # ansible.builtin.archive

core_dependencies__specific_packages: "{{
  _core_dependencies__specific_packages[ansible_distribution ~'_'~ ansible_distribution_major_version]|default(
  _core_dependencies__specific_packages[ansible_os_family ~'_'~ ansible_distribution_major_version])|default(
  _core_dependencies__specific_packages[ansible_distribution])|default(
  _core_dependencies__specific_packages[ansible_os_family])|default(
  _core_dependencies__specific_packages['default']) }}"

core_dependencies__packages: "{{ core_dependencies__shared_packages + core_dependencies__specific_packages }}"

core_dependencies__pip_packages:
  - boto
  - boto3
  - boto
