---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: debug output machine facts
      ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: compress /tmp
      community.general.archive:
        mode: u=rw,g=r,o=r
        path: /tmp
        dest: tmp.tgz

    - name: check network facts
      ansible.builtin.assert:
        that:
          - ansible_default_ipv4.broadcast is defined

    - name: see if the package manager still works
      block:
        - name: install a package
          ansible.builtin.package:
            name: acl
